const express = require('express');
const router = express.Router();
const capexController = require('../controllers/capexController');
const verifyToken = require('../middleware/auth');

router.get('/summary',         verifyToken, capexController.getSummary);
router.get('/departments',     verifyToken, capexController.getDepartmentsList);
router.get('/sync-status',     verifyToken, capexController.getSyncStatus);
router.get('/department/:name', verifyToken, capexController.getDepartment);
router.get('/gsap-data',       verifyToken, capexController.getGsapData);
router.get('/admin-config',    verifyToken, capexController.getAdminConfig);
router.patch('/admin-config/thresholds', verifyToken, capexController.updateThresholds);
router.patch('/admin-config/workflow-rules/:ruleId', verifyToken, capexController.updateWorkflowRule);
router.get('/process-reference', verifyToken, capexController.getProcessReferenceData);
router.get('/requests',        verifyToken, capexController.getRequests);
router.post('/requests',       verifyToken, capexController.createRequest);
router.get('/requests/report', verifyToken, capexController.getReport);
router.get('/reports/export', verifyToken, capexController.getReportExport);
router.get('/report-schedules', verifyToken, capexController.getReportSchedules);
router.post('/report-schedules', verifyToken, capexController.createReportSchedule);
router.get('/moa', verifyToken, capexController.getMoaRecords);
router.get('/dashboard/governance', verifyToken, capexController.getGovernanceDashboard);
router.get('/dashboard/drilldown', verifyToken, capexController.getDashboardDrilldown);
router.get('/requests/:id',    verifyToken, capexController.getRequestById);
router.post('/requests/:id/attachments', verifyToken, capexController.attachmentUploadMiddleware, capexController.uploadAttachment);
router.get('/requests/:id/attachments/:attachmentId/download', verifyToken, capexController.downloadAttachment);
router.patch('/requests/:id/decision', verifyToken, capexController.decideRequest);
router.patch('/requests/:id/procurement', verifyToken, capexController.updateProcurement);
router.post('/requests/:id/milestones', verifyToken, capexController.createMilestone);
router.patch('/requests/:id/milestones/:milestoneId', verifyToken, capexController.updateMilestone);
router.patch('/requests/:id/financial-closure', verifyToken, capexController.saveFinancialClosure);
router.patch('/requests/:id/auc', verifyToken, capexController.updateAucTracking);
router.patch('/requests/:id/capitalization', verifyToken, capexController.updateCapitalizationTracking);
router.patch('/requests/:id/po-closure', verifyToken, capexController.updatePoClosureTracking);
router.patch('/requests/:id/closure-checklist/:itemId', verifyToken, capexController.updateClosureChecklistItem);
router.post('/requests/:id/benefit-reviews', verifyToken, capexController.saveBenefitReview);
router.post('/requests/:id/risks', verifyToken, capexController.createRisk);
router.patch('/requests/:id/risks/:riskId', verifyToken, capexController.updateRisk);
router.post('/requests/:id/budget-variations', verifyToken, capexController.createBudgetVariation);
router.patch('/requests/:id/procurement-performance', verifyToken, capexController.saveProcurementPerformance);
router.patch('/requests/:id/decision-gates/:gateKey', verifyToken, capexController.updateDecisionGate);
router.post('/requests/:id/moa', verifyToken, capexController.saveMoaRecord);
router.post('/requests/:id/moa/:moaId/revisions', verifyToken, capexController.addMoaRevision);
router.post('/requests/:id/document-versions', verifyToken, capexController.createDocumentVersion);
router.post('/requests/:id/signatures', verifyToken, capexController.createElectronicSignature);
router.get('/requests/:id/audit', verifyToken, capexController.getAuditLogs);
router.get('/initiations',     verifyToken, capexController.getInitiations);
router.post('/initiations',    verifyToken, capexController.createInitiation);
router.get('/manual-entries',  verifyToken, capexController.getManualEntries);
router.post('/manual-entries', verifyToken, capexController.createManualEntry);

router.get('/budget-uploads',  verifyToken, capexController.getBudgetUploads);
router.post('/budget-upload',  verifyToken, capexController.csvUploadMiddleware, capexController.uploadBudget);

module.exports = router;
