const express = require('express');
const router = express.Router();
const capexController = require('../controllers/capexController');
const verifyToken = require('../middleware/auth');
const requirePermission = require('../middleware/requirePermission');

router.get('/summary',         verifyToken, requirePermission('capex.planning.dashboard'), capexController.getSummary);
router.get('/departments',     verifyToken, requirePermission('capex.planning.departments'), capexController.getDepartmentsList);
router.get('/sync-status',     verifyToken, requirePermission('capex.planning.dashboard'), capexController.getSyncStatus);
router.get('/department/:name', verifyToken, requirePermission('capex.planning.departments'), capexController.getDepartment);
router.get('/gsap-data',       verifyToken, requirePermission('capex.planning.dashboard'), capexController.getGsapData);
router.get('/admin-config',    verifyToken, requirePermission('capex.admin'), capexController.getAdminConfig);
router.patch('/admin-config/thresholds', verifyToken, requirePermission('capex.admin', 'can_edit'), capexController.updateThresholds);
router.patch('/admin-config/workflow-rules/:ruleId', verifyToken, requirePermission('capex.admin', 'can_edit'), capexController.updateWorkflowRule);
router.get('/process-reference', verifyToken, requirePermission('capex.governance.dashboard'), capexController.getProcessReferenceData);
router.get('/requests',        verifyToken, requirePermission('capex.requests'), capexController.getRequests);
router.post('/requests',       verifyToken, requirePermission('capex.requests', 'can_create'), capexController.createRequest);
router.get('/requests/report', verifyToken, requirePermission('capex.reports'), capexController.getReport);
router.get('/reports/export', verifyToken, requirePermission('capex.reports'), capexController.getReportExport);
router.get('/report-schedules', verifyToken, requirePermission('capex.reports'), capexController.getReportSchedules);
router.post('/report-schedules', verifyToken, requirePermission('capex.reports', 'can_create'), capexController.createReportSchedule);
router.get('/moa', verifyToken, requirePermission('capex.moa'), capexController.getMoaRecords);
router.get('/dashboard/governance', verifyToken, requirePermission('capex.governance.dashboard'), capexController.getGovernanceDashboard);
router.get('/dashboard/drilldown', verifyToken, requirePermission('capex.governance.dashboard'), capexController.getDashboardDrilldown);
router.get('/requests/:id',    verifyToken, requirePermission('capex.requests'), capexController.getRequestById);
router.patch('/requests/:id',  verifyToken, requirePermission('capex.requests', 'can_edit'), capexController.updateRequest);
router.post('/requests/:id/resubmit', verifyToken, requirePermission('capex.requests', 'can_edit'), capexController.resubmitRequest);
router.patch('/requests/:id/steps/:stepId/delegate', verifyToken, requirePermission('capex.approvals', 'can_edit'), capexController.delegateStep);
router.patch('/requests/:id/steps/:stepId/escalate', verifyToken, requirePermission('capex.approvals', 'can_edit'), capexController.escalateStep);
router.patch('/requests/:id/budget-variations/:variationId/decision', verifyToken, requirePermission('capex.approvals', 'can_edit'), capexController.decideBudgetVariation);
router.post('/requests/:id/attachments', verifyToken, requirePermission('capex.documents', 'can_create'), capexController.attachmentUploadMiddleware, capexController.uploadAttachment);
router.get('/requests/:id/attachments/:attachmentId/download', verifyToken, requirePermission('capex.documents'), capexController.downloadAttachment);
router.patch('/requests/:id/decision', verifyToken, requirePermission('capex.approvals', 'can_edit'), capexController.decideRequest);
router.patch('/requests/:id/procurement', verifyToken, requirePermission('capex.procurement', 'can_edit'), capexController.updateProcurement);
router.post('/requests/:id/milestones', verifyToken, requirePermission('capex.requests', 'can_edit'), capexController.createMilestone);
router.patch('/requests/:id/milestones/:milestoneId', verifyToken, requirePermission('capex.requests', 'can_edit'), capexController.updateMilestone);
router.patch('/requests/:id/financial-closure', verifyToken, requirePermission('capex.finance', 'can_edit'), capexController.saveFinancialClosure);
router.patch('/requests/:id/auc', verifyToken, requirePermission('capex.finance', 'can_edit'), capexController.updateAucTracking);
router.patch('/requests/:id/capitalization', verifyToken, requirePermission('capex.finance', 'can_edit'), capexController.updateCapitalizationTracking);
router.patch('/requests/:id/po-closure', verifyToken, requirePermission('capex.closure', 'can_edit'), capexController.updatePoClosureTracking);
router.patch('/requests/:id/closure-checklist/:itemId', verifyToken, requirePermission('capex.closure', 'can_edit'), capexController.updateClosureChecklistItem);
router.post('/requests/:id/benefit-reviews', verifyToken, requirePermission('capex.finance', 'can_edit'), capexController.saveBenefitReview);
router.post('/requests/:id/risks', verifyToken, requirePermission('capex.risks', 'can_create'), capexController.createRisk);
router.patch('/requests/:id/risks/:riskId', verifyToken, requirePermission('capex.risks', 'can_edit'), capexController.updateRisk);
router.post('/requests/:id/budget-variations', verifyToken, requirePermission('capex.variations', 'can_create'), capexController.createBudgetVariation);
router.patch('/requests/:id/procurement-performance', verifyToken, requirePermission('capex.procurement', 'can_edit'), capexController.saveProcurementPerformance);
router.patch('/requests/:id/decision-gates/:gateKey', verifyToken, requirePermission('capex.approvals', 'can_edit'), capexController.updateDecisionGate);
router.post('/requests/:id/moa', verifyToken, requirePermission('capex.moa', 'can_create'), capexController.saveMoaRecord);
router.post('/requests/:id/moa/:moaId/revisions', verifyToken, requirePermission('capex.moa', 'can_edit'), capexController.addMoaRevision);
router.post('/requests/:id/document-versions', verifyToken, requirePermission('capex.documents', 'can_create'), capexController.createDocumentVersion);
router.post('/requests/:id/signatures', verifyToken, requirePermission('capex.documents', 'can_create'), capexController.createElectronicSignature);
router.get('/requests/:id/audit', verifyToken, requirePermission('capex.documents'), capexController.getAuditLogs);
router.get('/initiations',     verifyToken, requirePermission('capex.initiations'), capexController.getInitiations);
router.post('/initiations',    verifyToken, requirePermission('capex.initiations', 'can_create'), capexController.createInitiation);
router.get('/manual-entries',  verifyToken, requirePermission('capex.tracking.manual-entry'), capexController.getManualEntries);
router.post('/manual-entries', verifyToken, requirePermission('capex.tracking.manual-entry', 'can_create'), capexController.createManualEntry);

router.get('/budget-uploads',  verifyToken, requirePermission('capex.finance'), capexController.getBudgetUploads);
router.post('/budget-upload',  verifyToken, requirePermission('capex.finance', 'can_create'), capexController.csvUploadMiddleware, capexController.uploadBudget);

module.exports = router;
